create table course(
    id integer generated by default as indentity primary key,
    course_id varchar(255),
    course_name varchar(255),
    course_price integer
);   

create table autor(
    id integer generated by default as identity primary key, 
    full_name varchar(255),
    website varchar(255)
);

insert into author (full_name, website) values
    ("JK", "loc.in"),
    ("Jay","loc.in");

insert into course (course_id, course_name, course_price) values 
    ('2', 'ReactJS', 499),
    ('1', 'TypeJS', 699);